version: 2
jobs:
  install_dependencies:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: |
          git config user.email "circleci@tpbowden.dev"
          git config user.name "circleci"
      - add_ssh_keys:
          fingerprints:
            - 16:6e:be:cf:17:8d:6b:a8:6d:db:45:f8:47:12:61:63
      - run: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
