version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.4

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: |
          git config user.email "circleci@tpbowden.dev"
          git config user.name "circleci"
      - add_ssh_keys:
          fingerprints:
            - 91:2c:9d:97:22:83:60:1e:da:b1:03:f7:db:5f:d6:26
      - run: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master
